# Generated by Django 6.0 on 2026-01-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces')], default='pcs', max_length=10),
        ),
    ]
