# Generated by Django 5.2.6 on 2026-01-17 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_created_at_product_updated_at_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product',
        ),
        migrations.AddField(
            model_name='listing',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопродление'),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, default='Not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_name',
            field=models.CharField(max_length=100, verbose_name='Контактное имя'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.listing')),
            ],
        ),
    ]
