# Generated by Django 5.2.6 on 2026-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.IntegerField(default=0, verbose_name='Расстояние (км)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пункт выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='storage_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок хранения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('shipping', 'Доставляется'), ('delivered', 'Доставлен'), ('picked-up', 'Выдан покупателю'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
