# Generated by Django 6.0 on 2026-02-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_cartitem_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
    ]
