# Generated by Django 6.0 on 2026-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_cartitem_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, default='Not specified', max_length=100, unique=True, verbose_name='Город доставки'),
        ),
    ]
