# Generated by Django 6.0 on 2026-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_order_delivery_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_distance',
            field=models.IntegerField(default=0, unique=True, verbose_name='Расстояние (км)'),
        ),
    ]
