# Generated by Django 6.0 on 2026-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_order_delivery_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='Not specified', max_length=100, verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_distance',
            field=models.IntegerField(default=0, verbose_name='Расстояние (км)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(default='Not specified', max_length=200, verbose_name='Пункт выдачи'),
        ),
    ]
