# Generated by Django 6.0 on 2026-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_distance',
            field=models.IntegerField(default=0, unique=True, verbose_name='Расстояние (км)'),
        ),
    ]
