# Generated by Django 6.0 on 2026-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
