# Generated by Django 5.2.6 on 2026-02-11 15:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код промокода', max_length=20, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент от суммы'), ('fixed', 'Фиксированная сумма'), ('free_shipping', 'Бесплатная доставка')], max_length=20, verbose_name='Тип скидки')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки ($)')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа ($)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальная сумма скидки ($)')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Оставьте пустым для безлимитного использования', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Лимит использований')),
                ('times_used', models.IntegerField(default=0, verbose_name='Использовано раз')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRandomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент от суммы'), ('fixed', 'Фиксированная сумма'), ('free_shipping', 'Бесплатная доставка')], max_length=20, verbose_name='Тип скидки')),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный процент')),
                ('max_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный процент')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма скидки ($)')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальная сумма скидки ($)')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа ($)')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='Лимит использований')),
                ('valid_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок действия (дней)')),
                ('code_prefix', models.CharField(blank=True, help_text='Например: SALE, PROMO, NEW', max_length=10, verbose_name='Префикс кода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон рандомайзера',
                'verbose_name_plural': 'Шаблоны рандомайзера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа ($)')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма скидки ($)')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email пользователя')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='pages.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'История использования промокодов',
                'ordering': ['-used_at'],
            },
        ),
    ]
