# Generated by Django 5.2.6 on 2026-02-12 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_promocode_promocoderandomizer_promocodeusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeusage',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='promocodeusage',
            name='user_email',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='promocoderandomizer',
            name='code_prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='Префикс кода'),
        ),
    ]
