# Generated by Django 6.0 on 2026-02-17 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_promocodeusage_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='listing',
        ),
        migrations.DeleteModel(
            name='PromoCodeRandomizer',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='pages_order_created_bd0300_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='pages_order_status_bd8d80_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='pages_order_user_id_c4f01c_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='Уникальный код промокода (например: SALE50, FREESHIP)', max_length=20, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True, help_text='Текст для клиента', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для фиксированной скидки', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки ($)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для процентной скидки (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ограничение для процентной скидки', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальная сумма скидки ($)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Минимум товаров для применения', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа ($)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='times_used',
            field=models.IntegerField(default=0, editable=False, verbose_name='Использовано раз'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit',
            field=models.IntegerField(blank=True, help_text='Оставьте пустым для безлимитного', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Лимит использований'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Оставьте пустым для бессрочного', null=True, verbose_name='Действителен до'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
    ]
