# Generated by Django 5.2.6 on 2026-02-19 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_listing_category_remove_listing_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Email-уведомления')),
                ('notif_push', models.BooleanField(default=False, verbose_name='Push-уведомления')),
                ('notif_sms', models.BooleanField(default=True, verbose_name='SMS-уведомления')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Тёмная тема')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('uz', "O'zbek")], default='ru', max_length=5, verbose_name='Язык')),
                ('volume', models.PositiveIntegerField(default=70, verbose_name='Громкость (%)')),
                ('analytics', models.BooleanField(default=True, verbose_name='Сбор аналитики')),
                ('twofa', models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
